name: Trigger auto deployment for node-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/node-test-AutoDeployTrigger-011e6e42-2efc-4a57-9df8-582be69ea827.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NODETEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NODETEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NODETEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: noderegistry1.azurecr.io
          registryUsername: ${{ secrets.NODETEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NODETEST_REGISTRY_PASSWORD }}
          containerAppName: node-test
          resourceGroup: indus-thienduong
          imageToBuild: noderegistry1.azurecr.io/node-test:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


